### ISSUE TITLE
Formatting issue with {{ in string

### ISSUE THREAD

**Issue by MSoegtropIMC** [LPCIC/coq-elpi-lang#1]
If a double brace is included in a string (`"{{"`), the following lines are formatted as string until a double closing brace in a string is encountered (`"}}"`),

**Comment by gares** [comment]
In which UI? vscode?

**Comment by gares** [comment]
hum, I guess my textmate foo is not very good ;-)

**Comment by MSoegtropIMC** [comment]
I was not aware that this can be used in other UIs - it is VSCode (well VSCodium to be precise).

**Comment by gares** [comment]
The bug comes from here:
https://github.com/LPCIC/coq-elpi-lang/blob/0db7ca37227918f57a4ff53e20e917612c57096c/syntaxes/coq-elpi-quotation.tmLanguage.json#L53-L62

**Comment by gares** [comment]
My original solution (in the Elpi and Coq parser) was to allow any number of `{` so that if you have a `"}}"` in you code you can just use `{{{` and `}}}` and be done with it.
But this engine is based on regexes, the `begin` and `end` values above, so the support is limited to 2 `{` and also it is not easy to be contextual (not within a string for example). I think they have a notion of comment, and maybe these are skipped for matching the `end`, but I'm not an expert.

**Comment by MSoegtropIMC** [comment]
I see. I guess this would probably get quite nasty to get right and is probably not worth the effort.

**Comment by gares** [comment]
The best I can suggest is to write `Msg is "}" ^ "}"` or something along these lines...

**Comment by MSoegtropIMC** [comment]
Or live with the very minor inconvenience of a slightly odd display ... I am not so sure I want to make the program more obscure for such reasons.

Shall I close or do you want to ponder over it?

**Comment by gares** [comment]
Wait, it may be easy: 
https://github.com/LPCIC/coq-elpi-lang/blob/0db7ca37227918f57a4ff53e20e917612c57096c/syntaxes/coq-elpi-quotation.tmLanguage.json#L77
says `-comment`, it should also say `-string` or something like that

**Comment by gares** [comment]
it works! I'll make a release

**Comment by MSoegtropIMC** [comment]
Great, thanks!

**Comment by gares** [comment]
should be live

**Comment by MSoegtropIMC** [comment]
Perfect - thanks! Works fine.

Btw.: it is mildly confusing that this change is not visible in the master branch - just the v0.0.5 tag.

**Comment by gares** [comment]
an oversight, thanks for reporting
